dataset:
  value: "fluids.compressible.Riemann"
input_time_len:
  value: 5
num_trajectories:
  value: 128
model_name:
  value: "B"
residual_model:
  value: "transformer"
lr:
  value: 0.0005
lr_embedding_recovery:
  value: 0.0005
lr_time_embedding:
  value: 0.0005
weight_decay:
  value: 0.000001
lr_scheduler:
  value: "cosine"
warmup_ratio:
  value: 0.0
early_stopping_patience:
  value: 200
num_epochs:
  value: 200
batch_size:
  value: 16
max_grad_norm:
  value: 5.0
